DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MUSEUMS' AND COLUMN_NAME = 'PHONE';
    IF column_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE MUSEUMS ADD (PHONE VARCHAR2(30))'; END IF;
    SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MUSEUMS' AND COLUMN_NAME = 'EMAIL';
    IF column_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE MUSEUMS ADD (EMAIL VARCHAR2(255))'; END IF;
    SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MUSEUMS' AND COLUMN_NAME = 'WEBSITE_URL';
    IF column_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE MUSEUMS ADD (WEBSITE_URL VARCHAR2(500))'; END IF;
END;
